### ISSUE TITLE
Ability to disable or enable Blob Cache

### ISSUE THREAD

**Issue by Jeavon** [umbraco/Umbraco.StorageProviders#15]
With this package currently ImageSharp.Web is configured to use blob storage for its cache by default. Without a proxy/cdn in front of the website, this means every image request requires the server to fetch the image from the blob cache which could be a lot of requests/bandwidth!

https://github.com/umbraco/Umbraco.StorageProviders/blob/d422db55e59e3f1d4138967552dc5881533e71bd/src/Umbraco.StorageProviders.AzureBlob/DependencyInjection/AzureBlobMediaFileSystemExtensions.cs#L48

My view is that using AzureBlobFileSystemImageCache should be an option to enable (with knowledge of the impact) so by default, the disk cache would be used. 

However as blob cache is currently the default with this package, perhaps an option should be added to disable it?

Many ways to do both of these....

Thoughts @rasmusjp @ronaldbarendse

**Comment by ronaldbarendse** [comment]
This is a valid point indeed, although re-populating the local disk cache (e.g. when the site is moved to another server/a new scale out instance is added) can also be very expensive. It will need to fetch all the original, potentially very large, images and process them again, which will use a fair amount of bandwidth and CPU as well.

ImageSharp also contains a LRU (Least Recently Used) in-memory cache to minimize the cache lookups ([which stores the last 1024 items for 5 minutes](https://github.com/SixLabors/ImageSharp.Web/blob/52bcb16fee6d600228769c459d961018ac9c2baa/src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs#L50-L54)).

The recommendation will be to use a CDN if this is an issue. If you want to revert back to the physical file cache, you can replace the `IImageCache` again after calling `AddAzureBlobMediaFileSystem()` for now:

```c#
builder.Services.AddUnique<IImageCache, PhysicalFileSystemCache>(); 
```

**Comment by Jeavon** [comment]
Agreed, generally, I would recommend blob cache is used when a reverse proxy or CDN is also in use. Many sites that use blob storage for media are hosted on VMs and disk cache can be preferable.
