### ISSUE TITLE
Crops are not working once the CDN Media Url provider is configured at startup.

### ISSUE THREAD

**Issue by dalemccutcheon** [umbraco/Umbraco.StorageProviders#22]
Hi,

![image](https://user-images.githubusercontent.com/40206347/138274577-69418b9f-f77a-4103-b01e-95c5ff67f8d2.png)

If we configure the site to use CDN Media URL provider the crops no longer crop as expected, these instead just return all the same size. Once this has been configured the returned path for the media files then looks like `https://{cdnUrl}/media/{mediafolder}/{imageName}?width=1280&height=540&rnd=132786959387800000` - which i'm not sure is correct as it does not appear to be using the cached file it creates in blob.

Also the cached file it creates in the "cache" blob container does not have a file extension therefore just has a key and is not actually `{filename}.jpg`.

If we remove the `.AddCdnMediaUrlProvider()` line from Startup then the cropping works as expected. 

In terms of rendering the image i have tried multiple ways :

```csharp
   var image = Url.GetCropUrl(Model.HeaderImage, 965, 700);
   var imageTest = Model.HeaderImage.GetCropUrl(1930, 1400);

   var image = Url.GetCropUrl(Model.HeaderImage, cropAlias: "headerImage");
   var imageTest = Model.HeaderImage.GetCropUrl(cropAlias: "headerImage");
```

**Comment by dalemccutcheon** [comment]
Hi @rasmusjp Any chance you guys have any other suggestions to look at? 

Cheers
Dale

**Comment by rasmusjp** [comment]
Hi @dalemccutcheon 

I've had a look at Azure CDN and found out that you'll need to change the query string caching behaviour rule to cache every unique url. This can be done on the endpoint caching rules. When you've made the change you'll need to purge the cache to ensure the non cropped images are removed

**Comment by dalemccutcheon** [comment]
@rasmusjp  thanks for the update i am trying this right now - the cdn is requesting images still with the blob container name i.e. {{cdn}}/{{blobContainer}}/media/gakjdfkgah/gjakfg when it should just be {{cdn}}/media/gakjdfkgah/gjakfg Do you know how i can fix that? 

Thanks
DAle

**Comment by rasmusjp** [comment]
Hi @dalemccutcheon

I think this might be the problem https://github.com/umbraco/Umbraco.StorageProviders/blob/d422db55e59e3f1d4138967552dc5881533e71bd/src/Umbraco.StorageProviders.AzureBlob/DependencyInjection/CdnMediaUrlProviderExtensions.cs#L36

You should be able to workaround this for now by setting the url in code

**Comment by dalemccutcheon** [comment]
When you say setting it in the code what do you mean? Where can i set that value?

**Comment by rasmusjp** [comment]
Hi @dalemccutcheon 

The `AddCdnMediaUrlProvider` takes a callback where you can configure the options, there's an example in the README

**Comment by ronaldbarendse** [comment]
> I think this might be the problem
> 
> https://github.com/umbraco/Umbraco.StorageProviders/blob/d422db55e59e3f1d4138967552dc5881533e71bd/src/Umbraco.StorageProviders.AzureBlob/DependencyInjection/CdnMediaUrlProviderExtensions.cs#L36

@rasmusjp Adding the container name to the configured URL here might indeed cause issues, as it would result in these examples having different CDN URLs:

```json
{
  "Umbraco": {
    "Storage": {
      "AzureBlob": {
        "Media": {
          "ConnectionString": "...",
          "ContainerName": "test",
          "Cdn": {
            "Url": "https://my-cdn.example.com/"
          }
        }
      }
    }
  }
}
```

The above would result in `https://my-cdn.example.com/test` being used as base CDN URL, but doing it in code will result in using that exact URL and thereby also not exposing the container name 😄 

```c#
.AddCdnMediaUrlProvider(options => {
    options.Url = new Uri("https://my-cdn.example.com/");
});
```

**Comment by ronaldbarendse** [comment]
@dalemccutcheon Besides trying to configure the CDN URL from code using the above example, also ensure you've updated the query string caching behavior to `Cache every unique URL`: https://docs.microsoft.com/en-us/azure/cdn/cdn-query-string (and purged/clear the CDN cache).

**Comment by dalemccutcheon** [comment]
Hey guys,

I think i have this working now there are a few different things i've had to change here such as removing app.UseStaticFiles() within the Startup.cs as well as app.UseResponseCaching() which appears to break the crops. 

I did also have to add this : -

.AddCdnMediaUrlProvider(options => {
    options.Url = new Uri("https://my-cdn.example.com/");
});

This seemed to fix the domain issue i was having. 

Cheers
Dale

**Comment by rasmusjp** [comment]
> @rasmusjp Adding the container name to the configured URL here might indeed cause issues, as it would result in these examples having different CDN URLs:

Yeah, we should probably remove it from this package since it's Cloud specific

**Comment by ronaldbarendse** [comment]
@rasmusjp PR for removing it is here: https://github.com/umbraco/Umbraco.StorageProviders/pull/24 👍🏻
