### ISSUE TITLE
Images in backoffice breaks using special characters like ë, version 9.3.1

### ISSUE THREAD

**Issue by jesperlange** [umbraco/Umbraco.StorageProviders#32]
**Bug Summary**
Certain characters like ë / Ë breaks the image and the url that's given to the image when it is drag&dropped into the media section
I haven't tested all special characters
This only happens on cloud.
Tested on 9.0.1, 9.2.0 and 9.3.1

![image](https://user-images.githubusercontent.com/54025229/157217869-09494193-0846-43a1-ab68-878e19027e74.png)

**Steps to reproduce:**
Drag and drop an image into the media section with a name including Ë/ë.

The request URL it gives:
https://testingbrokenimages.euwest01.umbraco.io/media/1mlphgts/%C3%ABgte.png

**Comment by ronaldbarendse** [comment]
I couldn't reproduce this using the latest source, only when using the latest released v1.0.0 version. Looking through the changes, I see PR https://github.com/umbraco/Umbraco.StorageProviders/pull/20 changed `request.Path` to `request.Path.Value`, which returns the decoded URL, so we don't end up double-encoding the file name and causing this issue.

We'll release a new version and coordinate the automatic update with the Cloud team shortly. We do want to include some other fixes as well, so I can't give you an exact date when this will be done.

While testing this using different characters (like `Ä`), I noticed some already got replaced by the characters configured in the [request handler settings](https://our.umbraco.com/Documentation/Reference/V9-Config/RequestHandlerSettings/) and thereby not cause this error to occur. This can be used as a temporary work-around (although it only applies to newly uploaded media) by adding the following to your `appsettings.json`:

```json
{
  "Umbraco": {
    "CMS": {
      "RequestHandler": {
        "ConvertUrlsToAscii": "try",
        "CharCollection": [
          {
            "Char": "ë",
            "Replacement": "e"
          },
          {
            "Char": "Ë",
            "Replacement": "E"
          }
          // Any other character that causes the issue
        ]
      }
    }
  }
}
```
