### ISSUE TITLE
use existing media folder on blob storage

### ISSUE THREAD

**Issue by davit20** [umbraco/Umbraco.StorageProviders#35]
Hi 
How I can use existing media folder on blob storage?

When I set "ContainerName": "media" it created the new media folder inside the existing blob storage media folder 
exp: media/media/xxxxx

Please help me with how I can use existing media folder 
exp: media/xxxxx

**Comment by ronaldbarendse** [comment]
As mentioned in the readme, media and cache files are stored in separate folders inside your Blob storage container. So if your container name is also `media`, then you would indeed end up with `/media/media...`. You can override this by setting the new `ContainerRootPath` option introduced in https://github.com/umbraco/Umbraco.StorageProviders/pull/20.

**Comment by hfloyd** [comment]
Can this setting be used to somehow support utilizing a v7 Media container on a v9 site? Or does a new Container need to be set up? https://our.umbraco.com/forum/using-umbraco-and-getting-started//109087-updating-site-from-umbraco-7-to-umbraco-9-existing-azure-blob-storage-media-showing-404s
