### ISSUE TITLE
Exception if container doesn't exist

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco.StorageProviders#6]
I just tried the StorageProvider in my solution and must say I am happy with the ease of setting it up, however I did run in a few problems I hope can be resolved.

When saving an image, if the container does not exist yet an error is thrown. Shouldn't the default behavior be to create the container if it not yet exists? Seeing as the provider relies on the existence of the container this seems pretty crucial.

Steps to reproduce:
1. install the package in an Umbraco site
2. point to a non existing container
3. try to upload an image

**Comment by ronaldbarendse** [comment]
We should indeed document it's required for the Azure Blob Storage container to exist 😄

I don't think we should automatically create it though (see [this ImageSharp discussion](https://github.com/SixLabors/ImageSharp.Web/pull/112#pullrequestreview-478423238)), but adding a `CreateIfNotExists()` helper method accepting an `AzureBlobFileSystemOptions` and `PublicAccessType` that can be called during application startup would make it an easy opt-in.

**Comment by rasmusjp** [comment]
Maybe add a boolean `CreateContainerIfNotExists` property on `AzureBlobFileSystemOptions` and handle it when the filesystem is created?
